# Generated by Django 4.0 on 2023-04-17 14:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=512, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=512, verbose_name='Название')),
                ('category_img', models.ImageField(upload_to='category-img/', verbose_name='Картинка')),
                ('category_desc', ckeditor.fields.RichTextField(verbose_name='Описание*')),
                ('slug', models.SlugField(verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=512, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=512, verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Страна производства',
                'verbose_name_plural': 'Странаы производства',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=512, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=512, verbose_name='Наименование*')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание*')),
                ('main_img', models.ImageField(upload_to='product-images/', verbose_name='Главное фото*')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product-images/', verbose_name='Фотография 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product-images/', verbose_name='Фотография 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product-images/', verbose_name='Фотография 3')),
                ('price', models.FloatField(default=0, verbose_name='Ценник(сум)')),
                ('trend', models.BooleanField(default=True, verbose_name='Тренд*')),
                ('stock', models.BooleanField(default=True, verbose_name='Наличие*')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Бренд*')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория*')),
                ('color', models.ManyToManyField(to='shop.Color', verbose_name='Цвет*')),
                ('made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country', verbose_name='Изготовление*')),
                ('size', models.ManyToManyField(to='shop.Size', verbose_name='Размер*')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
